name: "Олег Кислицын"
description: "Личный блог о разработке, крутых штуках и интересных наблюдениях."

url: "http://olegafx.ru"

excerpt_separator: ""
markdown: rdiscount
permalink: :year/:month/:title.html
highlighter: pygments

exclude: [node_modules, Gemfile, Rakefile, sass, bower.json, gulpfile.js, README.md]